### ISSUE TITLE
'Fields to keep' For Time Map Advanced tool causes tool to close

### ISSUE THREAD

**Issue by Chris-Hutch-iGeo** [traveltime-dev/traveltime-platform-qgis-plugin#29]
Seems to be an issue for 3.10 (works fine on 3.12)

When running the Time Map Advanced tool, using the 'Departure/Arrival fields to keep' fields causes the tool to close (once the fields have been selected and you click OK):

![image](https://user-images.githubusercontent.com/51789195/92627253-01257d00-f2c3-11ea-974e-4d7d9ad8290c.png)

**Comment by olivierdalang** [comment]
Does this still happen ? I just tried with 3.10.13 and can't reproduce the issue.

If it still happens, can you put some details (exact version of QGIS, OS, dataset if it only happens with certain datasets...)

**Comment by chris-traveltime** [comment]
All seems to be working as expected now!
