### ISSUE TITLE
Inputting data into the Batch tools causing the tools to close

### ISSUE THREAD

**Issue by Chris-Hutch-iGeo** [traveltime-dev/traveltime-platform-qgis-plugin#30]
Seems to be an issue for 3.10 (works fine on 3.12)

When selecting the layer to use in any of the Batch tools, using the 'Select from open layers...' option causes the tool to close (once the layer has been selected and you hit OK).

Looks like a very similar issue to the 'layers to keep' causing the Time Map Advanced tool to close

**Comment by olivierdalang** [comment]
Does this still happen ? I just tried with 3.10.13 and can't reproduce the issue.

If it still happens, can you put some details (exact version of QGIS, OS, dataset if it only happens with certain datasets...)

**Comment by chris-traveltime** [comment]
All seems to be working fine now!
