### ISSUE TITLE
INTERSECTION result aggregation type failing for multipolygon results (Time Map Simple and Time Map Advanced)

### ISSUE THREAD

**Issue by chris-traveltime** [traveltime-dev/traveltime-platform-qgis-plugin#33]
When running Time Map Simple or Time Map Advanced with the Result aggregation set as INTERSECTION, sometimes the following error occurs:

_Feature could not be written to results_46e3993a_b91d_4dac_9cd0_2eaf4157f804: Could not add feature with geometry type GeometryCollection to layer of type MultiPolygon_

Issue seems to persist in QGIS 3.10 also. Suspect it may be when the Intersection output is a multi-polygon.

**Comment by olivierdalang** [comment]
I think this happens when results contain lines or points (if two regions touch only by and edge or a node).

It should be easy to fix, but I'm not able to reproduce the issue, so I can't correctly test my fix. Are you able to share a dataset and algorithm parameters where this happens ?

**Comment by olivierdalang** [comment]
Ok I was able to reproduce and fix. Note that in the provided files, results are still empty (with default parameters of simple time map except mode set to INTERSECTION), as there's no intersection between all reachable zones.
