### ISSUE TITLE
Routes Simple and Routes Advanced returning a max string length error when using NORMAL or DURATION output styles

### ISSUE THREAD

**Issue by chris-traveltime** [traveltime-dev/traveltime-platform-qgis-plugin#34]
In QGIS 3.16, running Routes Simple or Routes Advanced using NORMAL or DURATION output styles, the following error is returned:

_Feature could not be written to results_912c925a_0772_41d8_b0e9_b6e7df46455b: Could not store attribute "prop_route": String of length 18158 exceeds maximum field length (255)_

Appears to be a similar issue to #32 where a new character limit is being imposed in 3.16.

May well also cause an issue when using the DETAILED output style, but as this gives the route in a turn-by-turn manner, the character lengths are much shorter in general.

**Comment by olivierdalang** [comment]
This should be fixed now (same issue as #32 indeed)
