### ISSUE TITLE
Time Map not displaying full radius

### ISSUE THREAD

**Issue by asloper1** [traveltime-dev/traveltime-platform-qgis-plugin#49]
I am investigating travel time from Airports in Australia. I have run a 1 hour driving time map from Gold Coast Airport (OOL in the image) and the output seems to suggest you can only go a few kms south from OOL within an hour. In reality I would expect this output to reach at least as far as Byron Bay on the southbound.

Grateful if you could investigate

![image](https://user-images.githubusercontent.com/108038011/175185979-b77860e7-3bab-402a-963b-7df2f147a661.png)

**Comment by chris-traveltime** [comment]
Thanks for flagging this! We are taking a look into the issue and will update here once resolved.

**Comment by chris-traveltime** [comment]
This is now resolved. 1-hour driving isochrone from Gold Coast Airport below:

<img width="817" alt="image" src="https://user-images.githubusercontent.com/72020226/175294340-78d9be5d-90c4-4b62-9043-e43b0db62e3c.png">
