### ISSUE TITLE
Add new parameters for time-map tools.

### ISSUE THREAD

**Issue by chris-traveltime** [traveltime-dev/traveltime-platform-qgis-plugin#51]
Add new parameters for the time-map tool (Simple and Advanced).

[level_of_detail](https://docs.traveltime.com/api/reference/isochrones#departure_searches-level_of_detail) - when configured, the _scale_type_ should be _simple_, with the user able to select the value from _lowest_ to _highest_

[single_shape](https://docs.traveltime.com/api/reference/isochrones#departure_searches-single_shape)

[no_holes](https://docs.traveltime.com/api/reference/isochrones#departure_searches-no_holes)

**Comment by olivierdalang** [comment]
Done in https://github.com/traveltime-dev/traveltime-platform-qgis-plugin/pull/65
