### ISSUE TITLE
Python error when loading map tiles

### ISSUE THREAD

**Issue by chris-traveltime** [traveltime-dev/traveltime-platform-qgis-plugin#54]
When loading map tiles using the 'Add a background layer' button in the toolbar, a python error is shown.

The tiles are loaded successfully into the browser despite the error.

<img width="655" alt="Screenshot 2022-12-20 at 11 23 31" src="https://user-images.githubusercontent.com/72020226/208655693-0eab5fc8-61d9-4500-a7b1-33ff4a2d0e58.png">

**Comment by aliciaoberholzer** [comment]
I am having the same issue
