### ISSUE TITLE
Update plugin branding

### ISSUE THREAD

**Issue by chris-traveltime** [traveltime-dev/traveltime-platform-qgis-plugin#55]
Update plugin branding from TravelTime Platform to TravelTime.

New brand assets to be provided.
<img width="128" alt="Screenshot 2022-12-19 at 16 30 06" src="https://user-images.githubusercontent.com/72020226/208656902-17c78496-945d-4ee0-b344-3d08930594ae.png">
<img width="242" alt="Screenshot 2022-12-19 at 16 31 28" src="https://user-images.githubusercontent.com/72020226/208656906-16ca64b4-9623-44de-adc6-a91c149e2ca0.png">

**Comment by chris-traveltime** [comment]
New brand assets.

Logo in the toolbar:
![TravelTime Logo Full (cropped)](https://user-images.githubusercontent.com/72020226/212655322-dc663867-06d0-467a-bdad-44915e8ce7da.png)

Logo in the plugin settings:
![TravelTime Logo Full (cropped)](https://user-images.githubusercontent.com/72020226/212655626-eab35c1a-254a-4484-a2b7-00c5f8f1762b.png)

**Comment by olivierdalang** [comment]
This was actually already done in https://github.com/traveltime-dev/traveltime-platform-qgis-plugin/pull/80 forgot to close the issue.
