### ISSUE TITLE
Implement experimental releases

### ISSUE THREAD

**Issue by chris-traveltime** [traveltime-dev/traveltime-platform-qgis-plugin#56]

**Comment by olivierdalang** [comment]
Just tested, this works already. I improved docs in [the readme](https://github.com/traveltime-dev/traveltime-platform-qgis-plugin#release) and tested with a 1.8.0 pre-release.

![image](https://user-images.githubusercontent.com/1894106/209689800-e66a5c24-76a4-4cc9-a4f4-977a72ee3c78.png)
